"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

Answer:
4613732

"""

#returns list of fib numbers up to n
def fib(n):
    lst = []
    i = 1
    lst.append(1)
    lst.append(2)
    while (lst[i] + lst[i-1]) < n:
        lst.append(lst[i]+lst[i-1])
        i = i + 1
    return lst

def sumfib(n):
    lst = fib(n)
    sum = 0
    j = 1
    x = len(lst)
    while j < x:
        sum = sum + lst[j]
        j = j + 3
    return sum
